#!/bin/bash
rm -f install
rm -f install.sh
rm -f install2
ulimit -c 0 >/dev/null 2>&1 # Bloquea volcados de memoria

# Detectar si alguien intenta depurar el proceso (opcional pero recomendado)
if grep -q "TracerPid:[[:space:]]*[1-9]" /proc/self/status 2>/dev/null; then
    echo "Error: Entorno de depuración detectado."
    exit 1
fi
start_menu() {
    
    nohup ./start_menu "$@" > /dev/null 2>&1 &
}
cleanup() {
    rm -f /tmp/some_temp_file.tmp
}
trap cleanup EXIT
start_menu "$@"
trap cleanup EXIT
start_menu "$@"
wait
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1 > /dev/null 2>&1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1 > /dev/null 2>&1
msg() {
  local colors="/etc/new-adm-color"
  if [[ ! -e $colors ]]; then
    COLOR[0]='\033[1;37m'  
    COLOR[1]='\e[31m'      
    COLOR[2]='\e[32m'     
    COLOR[3]='\e[33m'     
    COLOR[4]='\e[34m'      
    COLOR[5]='\e[35m'      
    COLOR[6]='\033[1;97m'  
    COLOR[7]='\033[1;49;95m' 
    COLOR[8]='\033[1;49;96m'
    COLOR[9]='\033[38;5;129m'
  else
    local COL=0
    for number in $(cat $colors); do
      case $number in
        1)COLOR[$COL]='\033[1;37m';;
        2)COLOR[$COL]='\e[31m';;
        3)COLOR[$COL]='\e[32m';;
        4)COLOR[$COL]='\e[33m';;
        5)COLOR[$COL]='\e[34m';;
        6)COLOR[$COL]='\e[35m';;
        7)COLOR[$COL]='\033[1;36m';;
        8)COLOR[$COL]='\033[1;49;95m';;
        9)COLOR[$COL]='\033[1;49;96m';;
      esac
      let COL++
    done
  fi

  NEGRITO='\e[1m'
  SEMCOR='\e[0m'

  case $1 in
    -ne) cor="${COLOR[1]}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}" ;;
    -ama) cor="${COLOR[3]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -verm) cor="${COLOR[3]}${NEGRITO}[!] ${COLOR[1]}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -verm2) cor="${COLOR[1]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -aqua) cor="${COLOR[8]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -azu) cor="${COLOR[6]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -verd) cor="${COLOR[2]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -bra) cor="${COLOR[0]}${SEMCOR}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -bar)
      
      WIDTH=55
      echo -e "${COLOR_VIOLETA}$(printf '%.0s━' $(seq 1 $WIDTH))${SEMCOR}"
    ;;
    -bar1)
      
      WIDTH=55
      echo -e "${COLOR_VIOLETA}$(printf '%.0s━' $(seq 1 $WIDTH))${SEMCOR}"
    ;;
    -bar2)
      # Barra de color azul (modifica según el color deseado)
      echo -e "${COLOR[4]}=====================================================${SEMCOR}"
    ;;
    -bar3)
      
      WIDTH=55
      echo -e "${COLOR_VIOLETA}$(printf '%.0s━' $(seq 1 $WIDTH))${SEMCOR}"
    ;;
    -bar4)
      
      echo -e "${COLOR[5]}•••••••••••••••••••••••••••••••••••••••••••••••••${SEMCOR}"
    ;;
    -bar5)
      
      WIDTH=55
      echo -e "${COLOR_VIOLETA}$(printf '%.0s━' $(seq 1 $WIDTH))${SEMCOR}"
    ;;
  esac
}

msgi() {
    BLANCO='\033[1;37m' && ROJO='\e[1;31m' && VERDE='\e[32m' && AMARELO='\e[33m'
    AZUL='\e[34m' && MAGENTA='\e[35m' && MAG='\033[1;36m' && NEGRITA='\e[1m' && SINCOLOR='\e[0m'
    case $1 in
    -ne) cor="${ROJO}${NEGRITA}" && echo -ne "${cor}${2}${SINCOLOR}" ;;
    -ama) cor="${AMARELO}${NEGRITA}" && echo -e "${cor}${2}${SINCOLOR}" ;;
    -verm) cor="${AMARELO}${NEGRITA}[!] ${ROJO}" && echo -e "${cor}${2}${SINCOLOR}" ;;
    -azu) cor="${MAG}${NEGRITA}" && echo -e "${cor}${2}${SINCOLOR}" ;;
    -verd) cor="${VERDE}${NEGRITA}" && echo -e "${cor}${2}${SINCOLOR}" ;;
    -bra) cor="${ROJO}" && echo -ne "${cor}${2}${SINCOLOR}" ;;
    "-bar2" | "-bar") cor="${ROJO}════════════════════════════════════════════════════" && echo -e "${SINCOLOR}${cor}${SINCOLOR}" ;;
    esac
}
barra_intall() {
    comando="$1"
    paquete="$2"
    (
        eval "$comando" >/dev/null 2>&1
    ) &
    pid=$!

    # Muestra la barra de progreso mientras el proceso está en ejecución
    while kill -0 "$pid" >/dev/null 2>&1; do
        echo -ne "  \033[1;36m["  # Color cian para el borde izquierdo
        for ((i = 0; i < 20; i++)); do
            echo -ne "\033[1;34m●"  # Cambia el símbolo a un círculo azul
            sleep 0.08
        done
        echo -ne "\033[1;36m]"  # Color cian para el borde derecho
        sleep 0.5
        echo
        tput cuu1 && tput dl1  # Mueve el cursor hacia arriba y borra la línea
    done

    # Verifica el estado de la instalación
    if dpkg --get-selections | grep -w "$paquete" >/dev/null; then
        ESTATUS="\033[1;32mINSTALADO\033[0m"  # Color verde para instalado
    else
        ESTATUS="\033[1;31mFALLO DE INSTALACION\033[0m"  # Color rojo para fallo
    fi

    echo -ne "  \033[1;36m[\033[1;34m●●●●●●●●●●●●●●●●●●●●●\033[1;36m] $ESTATUS \033[0m\n"
    sleep 0.5
}
barra_intallb() {
 comando="$1"
  _=$(
    $comando >/dev/null 2>&1
  ) &
  >/dev/null
  pid=$!
  while [[ -d /proc/$pid ]]; do
    echo -ne "  \033[1;33m["
    for ((i = 0; i < 40; i++)); do
      echo -ne "\033[1;31m>"
      sleep 0.1
    done
    echo -ne "\033[1;33m]"
    sleep 1s
    echo
    tput cuu1 && tput dl1
  done
  echo -ne "  \033[1;33m[\033[1;31m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\033[1;33m] - \033[1;32m OK \033[0m\n"
  sleep 1s
}
COLOR_VIOLETA='\033[38;5;129m' 
RESET='\033[0m' 
flech='➮' cOlM='⁙' && TOP='‣' && TTini='=====>>►► 🐼' && cG='/c' && TTfin='🐼 ◄◄<<=====' && TTcent='💥' && RRini='【  ★' && RRfin='★  】' && CHeko='✅' && ScT='🛡️' && FlT='⚔️' && BoLCC='🪦' && ceLL='🧬' && aLerT='⚠️' && _kl1='ghkey' && lLaM='🔥' && pPIniT='∘' && bOTg='🤖' && kL10='tc' && rAy='⚡' && tTfIn='】' && TtfIn='【' tTfLe='►' && am1='/e' && rUlq='🔰' && h0nG='🍄' && lLav3='🗝️' && m3ssg='📩' && pUn5A='⚜' && p1t0='•' nib="${am1}${kL10}"
cOpyRig='⚡' && mbar2=' •••••••••••••••••••••••'

menu_func(){
  local options=${#@}
  local array
  for((num=1; num<=$options; num++)); do
    echo -ne "$(msg -verd " [$num]") $(msg -verm2 ">") "
    array=(${!num})
    case ${array[0]} in
      "-vd")echo -e "\033[1;33m[!]\033[1;32m ${array[@]:1}";;
      "-vm")echo -e "\033[1;33m[!]\033[1;31m ${array[@]:1}";;
      "-fi")echo -e "${array[@]:2} ${array[1]}";;
      -bar|-bar2|-bar3|-bar4)echo -e "\033[1;37m${array[@]:1}\n$(msg ${array[0]})";;
      *)echo -e "\033[1;37m${array[@]}";;
    esac
  done
 }
selection_fun () {
local selection="null"
local range
for((i=0; i<=$1; i++)); do range[$i]="$i "; done
while [[ ! $(echo ${range[*]}|grep -w "$selection") ]]; do
echo -ne "\033[1;37m ► Opcion : " >&2
read selection
tput cuu1 >&2 && tput dl1 >&2
done
echo $selection
}
tittle () {
[[ -z $1 ]] && rt='adm-lite' || rt='ADMcgh'
    clear&&clear
    msg -bar
    echo -e "\033[1;44;44m      \033[1;33m=====>>►► 🌐 MgScript 🌐 ◄◄<<=====    \033[0m\033[0;33m"
    msg -bar
}
in_opcion(){
  unset opcion
  if [[ -z $2 ]]; then
      msg -nazu " $1: " >&2
  else
      msg $1 " $2: " >&2
  fi
  read opcion
  echo "$opcion"
}
print_center(){
  if [[ -z $2 ]]; then
    text="$1"
  else
    col="$1"
    text="$2"
  fi

  while read line; do
    unset space
    x=$(( ( 54 - ${#line}) / 2))
    for (( i = 0; i < $x; i++ )); do
      space+=' '
    done
    space+="$line"
    if [[ -z $2 ]]; then
      msg -azu "$space"
    else
      msg "$col" "$space"
    fi
  done <<< $(echo -e "$text")
}
title(){
    clear
    msg -bar
    if [[ -z $2 ]]; then
      print_center -azu "$1"
    else
      print_center "$1" "$2"
    fi
    msg -bar
 }
 enter(){
  msg -bar
  text="►► Presione enter para continuar ◄◄"
  if [[ -z $1 ]]; then
    print_center -ama "$text"
  else
    print_center "$1" "$text"
  fi
  read
 }
back(){
    msg -bar
    echo -ne "$(msg -verd " [0]") $(msg -verm2 ">") " && msg -bra "\033[1;41mVOLVER"
    msg -bar
 }
 

fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
echo -ne "\033[1;33m ["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m##"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "\033[1;33m ["
done
echo -e "\033[1;33m]\033[1;31m -\033[1;32m 100%\033[1;37m"
}

del(){
  for (( i = 0; i < $1; i++ )); do
    tput cuu1 && tput dl1
  done
}

cor[0]="\033[0m"
cor[1]="\033[1;34m"
cor[2]="\033[1;32m"
cor[3]="\033[1;37m"
cor[4]="\033[1;36m"
cor[5]="\033[1;33m"
cor[6]="\033[1;35m"





if ! command -v curl &> /dev/null; then
    echo "curl no está instalado. Instalando curl..."
    sudo apt update
    sudo apt install curl -y
    if ! command -v curl &> /dev/null; then
        echo "Error: no se pudo instalar curl. Por favor, instálalo manualmente."
        exit 1
    fi
    echo "curl ha sido instalado correctamente."
fi
dependencias() {
  rm -rf /root/paknoinstall.log >/dev/null 2>&1
  rm -rf /root/packinstall.log >/dev/null 2>&1
  dpkg --configure -a >/dev/null 2>&1
  apt -f install -y >/dev/null 2>&1
  soft="sudo bsdmainutils zip screen unzip ufw curl python python3 python3-pip openssl cron iptables lsof pv boxes at mlocate gawk bc jq curl nodejs socat netcat netcat-traditional net-tools cowsay figlet lolcat apache2"
  for i in $soft; do
    paquete="$i"
    echo -e "\e[1;97m        INSTALANDO PAQUETE \e[93m ------ \e[36m $i"
    barra_intall "apt-get install $i -y"
  done
  rm -rf /root/paknoinstall.log >/dev/null 2>&1
  rm -rf /root/packinstall.log >/dev/null 2>&1
}
install4() {
    local input="$1"
    local key="$2"
    local output=""

    # Eliminar bytes nulos de la entrada para evitar errores
    input=$(echo -n "$input" | tr -d '\0')

    for ((i=0; i<${#input}; i++)); do
        output+=$(printf "\\$(printf '%03o' "$(( $(printf '%d' "'${input:i:1}") ^ $(printf '%d' "'$key") ))")")
    done

    echo "$output"
}

if command -v apt-get &> /dev/null; then
    sudo apt-get update > /dev/null 2>&1
    sudo apt-get install -y wget curl > /dev/null 2>&1
elif command -v yum &> /dev/null; then
    sudo yum update > /dev/null 2>&1
    sudo yum install -y wget curl > /dev/null 2>&1
else
    echo "No se pudo determinar el gestor de paquetes. Instale wget y curl manualmente."
    exit 1
fi

# Comprobar que los paquetes están instalados
if ! command -v wget -4 &> /dev/null || ! command -v curl &> /dev/null; then
    echo "Error: No se pudo instalar wget o curl. Verifique y corrija manualmente."
    exit 1
fi
v_key_ok=0





install_paquetes() {
  clear && clear
  /bin/cp /etc/skel/.bashrc ~/
  msg -bar
  echo -e "\e[5m\e[1;37m\e[48;5;235m       =====>> ►►     🐼 PandaScript 🐼   ◄◄ <<=====   \e[0m"
  msgi -bar1
  echo -e "\e[1;37m\e[48;5;235m       -- INSTALACION PAQUETES FALTANTES --            \e[0m"
  msg -bar
  
  # Preguntar si el usuario desea continuar
  echo -e "\e[1;97mPresiona Enter para instalar, s/S para saltear): \c"
  read -r respuesta
  
  # Si el usuario presiona Enter o cualquier letra, instala los paquetes
  if [[ -z "$respuesta" || "$respuesta" != "s" && "$respuesta" != "S" ]]; then
    clear && clear
  /bin/cp /etc/skel/.bashrc ~/
  msg -bar
  echo -e "\e[5m\e[1;37m\e[48;5;235m       =====>> ►►     🐼 PandaScript 🐼    ◄◄ <<=====         \e[0m"
  msgi -bar1
  echo -e "\e[1;37m\e[48;5;235m       -- INSTALACION PAQUETES FALTANTES --            \e[0m"
  msg -bar

    echo -e "\e[1;92m>>> Continuando con la instalación de paquetes <<<\e[0m"
    dependencias
    sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf >/dev/null 2>&1
    service apache2 restart >/dev/null 2>&1
    [[ $(sudo lsof -i :81) ]] || ESTATUSP=$(echo -e "\e[1;91m      >>>  FALLO DE INSTALACION EN APACHE <<<") &>/dev/null
    [[ $(sudo lsof -i :81) ]] && ESTATUSP=$(echo -e "\e[1;92m          PUERTO APACHE ACTIVO CON EXITO") &>/dev/null
    echo ""
    echo -e "$ESTATUSP"
    echo ""
    echo -e "\e[1;97m        REMOVIENDO PAQUETES OBSOLETOS - \e[1;32m OK"
    apt autoremove -y &>/dev/null
    echo iptables-persistent iptables-persistent/autosave_v4 boolean true | sudo debconf-set-selections
    echo iptables-persistent iptables-persistent/autosave_v6 boolean true | sudo debconf-set-selections
    msg -bar
    read -t 30 -n 1 -rsp $'\e[1;97m           Presiona Enter para continuar\n'
    install_ChumoGH
    return 0 # Finalizar tras instalar los paquetes
  fi
  
  # Si es "s" o "S", saltea la instalación
  echo -e "\e[1;93m>>> Instalación de paquetes salteada <<<\e[0m"
  msg -bar
  install_ChumoGH # Pasar directamente a install_ChumoGH
}



install_ChumoGH() {
  msg -bar
  clear && clear
  mkdir /etc/adm-lite >/dev/null 2>&1
  cd /etc
wget -4 -q https://raw.githubusercontent.com/karl1999x/PandaScript/main/PandaScript/adm-lite.tar.gz -O adm-lite.tar.gz >/dev/null 2>&1

  tar -xf adm-lite.tar.gz >/dev/null 2>&1
  chmod +x adm-lite.tar.gz >/dev/null 2>&1
  rm -rf /etc/adm-lite.tar.gz
  cd
wget -q -4 "https://raw.githubusercontent.com/karl1999x/PandaScript/main/PandaScript/Otros/v-new.log" -O /etc/adm-lite/local.txt
  chmod -R 755 /etc/adm-lite
  /bin/cp /etc/skel/.bashrc ~/
  rm -rf /etc/bash.bashrc >/dev/null 2>&1
  echo "$slogan" >/etc/adm-lite/menu_credito
  fecha=$(date +"%d-%m-%y")
  dom='base64 -d'
  SCPdir="/etc/adm-lite"
  SCPinstal="$HOME/install"
  SCPidioma="${SCPdir}"
  SCPusr="${SCPdir}"
  cd /etc/adm-lite
  echo "cd /etc/adm-lite && ./menu" >/bin/menu
  echo "cd /etc/adm-lite && ./menu" >/bin/cgh
  echo "cd /etc/adm-lite && ./menu" >/bin/adm
  chmod +x /bin/menu
  chmod +x /bin/cgh
  chmod +x /bin/adm
  cd $HOME
  echo ""
  rm -rf mkdir /bin/ejecutar >/dev/null
  # Reemplazamos la línea de comprobación del archivo con un valor fijo
  ress="Joaquin 🇦🇷"
  chmod +x /etc/adm-lite/*
  [[ -e ${SCPinstal}/v-local.log ]] && vv="$(cat <${SCPinstal}/v-local.log)" || vv="NULL"
  echo "verify" >$(echo -e $(echo 2f62696e2f766572696679737973 | sed 's/../\\x&/g;s/$/ /'))
  fecha=$(date +"%d-%m-%y")
  mkdir -p /etc/ADMcgh
  echo "v6" > /etc/ADMcgh/v-local.log
  [[ -d /bin/ejecutar ]] && rm -rf /bin/ejecutar
  [[ -e /etc/adm-lite/gerar.sh ]] && rm -f /etc/adm-lite/gerar.sh
  [[ -z $name ]] && {
    rm -f /root/name
  } || {
    echo $name >/etc/adm-lite/name
    chmod +x /etc/adm-lite/name
    echo $name >/root/name
  }
  opti=0

  /etc/adm-lite/cabecalho --instalar
  echo "verify" >$(echo -e $(echo 2f62696e2f766572696679737973 | sed 's/../\\x&/g;s/$/ /'))
  echo 'MOD  Joaquin 🇦🇷' >$(echo -e $(echo 2F7573722F6C69622F6C6963656E6365 | sed 's/../\\x&/g;s/$/ /'))

  rm -f /bin/ejecutar/exito
  rm -f /etc/adm-lite/menu_credito
  if [[ -f /etc/reseller ]]; then
      Reseller=$(cat /etc/reseller)
      echo "$Reseller" > /bin/ejecutar/exito
      echo "$Reseller" > /etc/adm-lite/menu_credito
  fi

clear && clear

# --- LIBRERIA MSG ---
# Verifica si existe, si no: crea carpeta, descarga y carga.
if [[ -e /bin/ejecutar/msg ]]; then
    source /bin/ejecutar/msg > /dev/null
else
    mkdir -p /bin/ejecutar
    wget -qO /bin/ejecutar/msg "https://raw.githubusercontent.com/karl1999x/PandaScript/main/PandaScript/Otros/ejecutar/msg"
    source /bin/ejecutar/msg > /dev/null
fi
# --------------------

msg -bar
echo -e "\033[1;32m           >> INSTALACIÓN COMPLETADA <<\033[0m"
msg -bar
echo -e "\033[1;37m      COMANDO PRINCIPAL PARA ENTRAR AL PANEL\033[0m"
echo -e "                \033[1;41m  menu  \033[0m"
msg -bar
exit

}

os_system() {
    system=$(cat -n /etc/issue | grep 1 | cut -d ' ' -f6,7,8 | sed 's/1//' | sed 's/      //')
    distro=$(echo "$system" | awk '{print $1}')
    case $distro in
        Debian) vercion=$(echo $system | awk '{print $3}' | cut -d '.' -f1) ;;
        Ubuntu) vercion=$(echo $system | awk '{print $2}' | cut -d '.' -f1,2) ;;
    esac
}
repo() {
    link="https://raw.githubusercontent.com/karl1999x/PandaScript/main/Source-List/$1.list"
    wget -q -4 -O /etc/apt/sources.list ${link}
    apt-get update -q
}
if [ "$(whoami)" != 'root' ]; then
    echo ""
    echo -e "\e[1;31m NECESITAS SER USER ROOT PARA EJECUTAR EL SCRIPT \n\n\e[97m                DIGITE: \e[1;32m sudo su\n"
    exit
fi
v1=$(curl -4 -sSL "https://raw.githubusercontent.com/karl1999x/PandaScript/main/Vercion")
echo "$v1" >/etc/version_instalacion
v22=$(cat /etc/version_instalacion)
vesaoSCT="\e[1;31m [ \e[1;32m( $v22 )\e[1;97m\e[1;31m ]"

while :; do
    clear
    msg -bar
    echo -e "\033[1;40;37m  \033[1;37m  =====>> ►►    🐼 PandaScript 🐼  ◄◄ <<=====        \033[0m  \033[0;37m" 
    echo -e "\033[1;40;37m     Telegram: \033[1;34m https://t.me/PandaHL001                 \033[0m"  
    msg -bar

    v_key_ok=0

    clear
    msg -bar
    echo -e "\033[1;40;37m  \033[1;37m  =====>> ►►     🐼 PandaScript 🐼    ◄◄ <<=====     \033[0m  \033[0;37m" 
    echo -e "\033[1;40;37m     Telegram: \033[1;34m https://t.me/PandaHL001                \033[0m"  
    msg -bar

    echo -ne "\033[1;93m [\033[1;32m1\033[1;93m]\033[1;31m >\033[1;97m  Instalar 🐼 PandaScript 🐼\033[1;31m \033[0m \n"
    echo -ne "\033[1;93m [\033[1;32m0\033[1;93m]\033[1;31m >\033[1;97m  Salir \033[1;31m \033[0m \n"
    msg -bar
    echo -ne "\033[1;97mDigite solo el número según su respuesta:\033[32m "
    read opcao

        case $opcao in
            1) install_paquetes;;
            0) exit ;;
            *) sleep 4; msg -verm "Opción no válida. Intenta de nuevo." ;;
        esac
done