#!/bin/bash
#CREADOR Henry Chumo | 25/08/2022 | MOD PandaScript
#Alias : @ChumoGH
# -*- ENCODING: UTF-8 -*-
export PATH=$PATH:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/sbin:/bin:/usr/games;
fecha=`date +"%d-%m-%y"`;
SCPdir="/etc/adm-lite"
SCPinstal="$HOME/install"
# Repositorio GitHub del proyecto
GITHUB_RAW="https://raw.githubusercontent.com/martincho247/PandaScript/main/PandaScript"

rm -f instala.*
[[ -e /etc/folteto ]] && rm -f /etc/folteto

echo -e " ESPERE UN MOMENTO "
apt-get install curl -y &>/dev/null
apt install sudo -y &> /dev/null
mkdir -p /bin/ejecutar
[[ -e /bin/ejecutar/msg ]] || wget -q -O /bin/ejecutar/msg "${GITHUB_RAW}/Otros/msg"
source /bin/ejecutar/msg > /dev/null 2>&1
COLS=$(tput cols)

os_system() {
 system=$(cat -n /etc/issue |grep 1 |cut -d ' ' -f6,7,8 |sed 's/1//' |sed 's/      //')
 distro=$(echo "$system"|awk '{print $1}')
 case $distro in
 Debian)vercion=$(echo $system|awk '{print $3}'|cut -d '.' -f1);;
 Ubuntu)vercion=$(echo $system|awk '{print $2}'|cut -d '.' -f1,2);;
 esac
 link="https://raw.githubusercontent.com/martincho247/PandaScript/main/Source-List/${vercion}.list"
}

if ! [ $(id -u) = 0 ]; then
    clear
    echo ""
    echo " _________________________________________________"
    echo "	Error Fatal!!"
    echo " _________________________________________________"
    echo " Este script debe ejecutarse como root!"
    echo " _________________________________________________"
    echo " Como Solucionarlo "
    echo " Ejecuta el script como:"
    echo "                              (  sudo -i )"
    echo "	                                sudo su"
    echo "	                             Retornando . . ."
    echo $(date)
    exit 1
fi

act_ufw() {
    [[ -f "/usr/sbin/ufw" ]] && ufw allow 81/tcp ; ufw allow 8888/tcp
}

fun_ip () {
    MIP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
    MIP2=$(wget -qO- ipv4.icanhazip.com)
    [[ "$MIP" != "$MIP2" ]] && IP="$MIP2" || IP="$MIP"
}

function_verify () {
    echo "verify" > $(echo -e $(echo 2f62696e2f766572696679737973|sed 's/../\\x&/g;s/$/ /'))
    echo 'MOD @MgScript' > $(echo -e $(echo 2F7573722F6C69622F6C6963656E6365|sed 's/../\\x&/g;s/$/ /'))
    [[ $(dpkg --get-selections|grep -w "libpam-cracklib"|head -1) ]] || apt-get install libpam-cracklib -y &> /dev/null
    echo -e '# Modulo @MgScript
password [success=1 default=ignore] pam_unix.so obscure sha512
password requisite pam_deny.so
password required pam_permit.so' > /etc/pam.d/common-password && chmod +x /etc/pam.d/common-password
}

valid_fun () {
    msg -bar
    echo -e "${cor[2]}\n\033[1;37m  Script Patrocinado por: @MgScript - " | pv -qL 12
    msg -bar
    echo -e "  ${cor[5]} NewScriptADM Mod MgScript-ADM REFACTORIZADO "
    msg -bar
    echo -e "${cor[3]}     DESENCADENANDO FICHEROS DEL SISTEMA "
    echo '#!/bin/bash
SCPdir="/etc/adm-lite"
cd ${SCPdir} && ./menu' > /bin/menu && chmod +x /bin/menu
    echo '#!/bin/bash
SCPdir="/etc/adm-lite"
cd ${SCPdir} && ./menu' > /bin/cgh && chmod +x /bin/cgh
    echo '#!/bin/bash
SCPdir="/etc/adm-lite"
cd ${SCPdir} && ./menu' > /bin/adm && chmod +x /bin/adm
    msg -bar
    [[ -e ${SCPdir}/menu_credito ]] && ress="$(cat ${SCPdir}/menu_credito) " || ress="NULL ( no found ) "
    echo -ne "${cor[2]}\n\033[1;37m  RESELLER  : " | pv -qL 50 && sleep 1s && echo -e "\033[0;35m$ress" | pv -qL 50
    [[ -e ${SCPdir}/cabecalho ]] && bash ${SCPdir}/cabecalho --instalar
}

error_conex () {
    clear&&clear
    msg -bar
    echo -e "\e[3;31m   CONEXION FALLIDA  COMANDO MANUAL :  sudo apt  update" | pv -qL 50
    msg -bar3
    echo -e "\e[5m\e[1;37m\e[48;5;235m      =====>> ►►     🌐 MgScript 🌐   ◄◄ <<=====   \e[0m"
    msg -bar3
    echo -e "\033[1;33m   EL PROBLEMA FUE UNA FALLA DE ACTUALIZACION DE SISTEMA "
    sleep 12s
    exit 1
}

invalid_key () {
    msg -bar
    echo -e "\e[3;31m  La instalacion no pudo completarse correctamente" | pv -qL 50
    sleep 3
    exit 1
}

# ============================================================
# INSTALACION SIN KEY: descarga y monta todo desde GitHub
# ============================================================
funkey () {
    clear&&clear
    msg -bar3
    echo -e "\e[5m\e[1;37m\e[48;5;235m      =====>> ►►  🌐 MgScript 🌐  ◄◄ <<=====   \e[0m"
    msg -bar3
    msg -bar
    echo -e "\033[1;33m   DESCARGANDO E INSTALANDO PandaScript DESDE GITHUB ..."
    [[ ! -d ${SCPdir} ]] && mkdir -p ${SCPdir}
    [[ ! -d /etc/adm-lite/slow ]] && mkdir -p /etc/adm-lite/slow
    [[ ! -d /etc/ADMcgh ]] && mkdir -p /etc/ADMcgh

    cd /etc
    echo " > obteniendo adm-lite.tar.gz ..."
    if wget -q -4 "${GITHUB_RAW}/adm-lite.tar.gz" -O adm-lite.tar.gz; then
        tar -xf adm-lite.tar.gz >/dev/null 2>&1
        # Forzar descarga del cabecalho y menu actualizados desde GitHub
wget -q -4 "${GITHUB_RAW}/adm-lite/cabecalho" -O ${SCPdir}/cabecalho
wget -q -4 "${GITHUB_RAW}/adm-lite/menu" -O ${SCPdir}/menu
chmod +x ${SCPdir}/cabecalho ${SCPdir}/menu
        chmod -R +x ${SCPdir} 2>/dev/null
        rm -f adm-lite.tar.gz
    else
        echo "   ! FALLO al descargar adm-lite.tar.gz"
        invalid_key
    fi

    cd ${SCPdir}
    wget -q -4 "${GITHUB_RAW}/install2" -O install2 && chmod +x install2
    wget -q -4 "${GITHUB_RAW}/menu_inst" -O menu_inst && chmod +x menu_inst
    wget -q -4 "${GITHUB_RAW}/Otros/v-new.log" -O /etc/adm-lite/local.txt 2>/dev/null
    [[ ! -s /etc/adm-lite/local.txt ]] && echo "v6=1.4.60" > /etc/adm-lite/local.txt

    mkdir -p /bin/ejecutar
    wget -q -O /bin/ejecutar/msg "${GITHUB_RAW}/Otros/ejecutar/msg" 2>/dev/null || cp -f ${SCPdir}/Otros/msg /bin/ejecutar/msg 2>/dev/null
    chmod +x /bin/ejecutar/msg 2>/dev/null

    echo "Verified【 MgScript" > /bin/ejecutar/exito
    echo "v6=1.4.60" > /bin/ejecutar/v-new.log
    echo "0" > /bin/ejecutar/uskill
    echo "PandaHL001" > /etc/cghkey
    IP=$(wget -q -4 -O - http://ipv4.icanhazip.com 2>/dev/null | tr -d '[:space:]')
    [[ -z "$IP" ]] && IP=$(ip addr | grep 'inet ' | grep -v 127.0.0.1 | awk '{print $2}' | cut -d/ -f1 | head -1)
    echo "$IP" > /bin/ejecutar/IPcgh
    echo "$fecha" > /bin/ejecutar/fecha
    free -h | grep Mem | sed 's/\s\+/,/g' | cut -d , -f4 > /bin/ejecutar/raml
    [[ -e ${SCPdir}/menu_credito ]] && cat ${SCPdir}/menu_credito > /bin/ejecutar/menu_credito || echo "MgScript" > /bin/ejecutar/menu_credito
    chmod +x /bin/ejecutar/* 2>/dev/null

    echo "v6" > /etc/ADMcgh/v-local.log
    echo "v6" > /etc/adm-lite/v-local.log
    echo "v6=1.4.60" > /etc/adm-lite/local.txt

    echo '#!/bin/bash
SCPdir="/etc/adm-lite"
cd ${SCPdir} && ./menu' > /bin/menu && chmod +x /bin/menu
    echo '#!/bin/bash
SCPdir="/etc/adm-lite"
cd ${SCPdir} && ./menu' > /bin/cgh && chmod +x /bin/cgh
    echo '#!/bin/bash
SCPdir="/etc/adm-lite"
cd ${SCPdir} && ./menu' > /bin/adm && chmod +x /bin/adm

    chmod -R 755 ${SCPdir}
    chmod +x ${SCPdir}/usercodes ${SCPdir}/menu ${SCPdir}/ferramentas ${SCPdir}/cabecalho 2>/dev/null
    msg -bar
    echo -e "\033[1;32m           >> PandaScript DESCARGADO <<\033[0m"
    msg -bar
}

update_pak () {
    echo ""
    [[ $(dpkg --get-selections|grep -w "pv"|head -1) ]] || apt install pv -y &> /dev/null
    os_system
    echo -e "		[ ! ]  ESPERE UN MOMENTO  [ ! ]"
    [[ $(dpkg --get-selections|grep -w "lolcat"|head -1) ]] || apt-get install lolcat -y &>/dev/null
    [[ $(dpkg --get-selections|grep -w "figlet"|head -1) ]] || apt-get install figlet -y &>/dev/null
    echo ""
    msg -bar
    echo -e "\e[1;31m  SISTEMA:  \e[33m$distro $vercion \e[1;31m	CPU:  \e[33m$(lscpu | grep "Vendor ID" | awk '{print $3}')"
    msg -bar
    dpkg --configure -a > /dev/null 2>&1 && echo -e "\033[94m    ${TTcent} INTENTANDO RECONFIGURAR UPDATER ${TTcent}" | pv -qL 80
    msg -bar
    echo -e "\033[94m    ${TTcent} UPDATE DATE : $(date +"%d/%m/%Y") & TIME : $(date +"%H:%M") ${TTcent}" | pv -qL 80
    [[ $(dpkg --get-selections|grep -w "net-tools"|head -1) ]] || apt-get install net-tools -y &>/dev/null
    [[ $(dpkg --get-selections|grep -w "boxes"|head -1) ]] || apt-get install boxes -y &>/dev/null
    [[ $(dpkg --get-selections|grep -w "screen"|head -1) ]] || apt-get install screen -y &>/dev/null
    [[ $(dpkg --get-selections|grep -w "stunnel4"|head -1) ]] || apt-get install stunnel4 -y &>/dev/null
    [[ $(dpkg --get-selections|grep -w "python2"|head -1) ]] || apt-get install python2 -y &>/dev/null
    echo ""
    apt-get install software-properties-common -y > /dev/null 2>&1 && echo -e "\033[94m    ${TTcent} INSTALANDO NUEVO PAQUETES ( S|P|C )    ${TTcent}" | pv -qL 80
    echo ""
    echo -e "\033[94m    ${TTcent} PREPARANDO BASE RAPIDA INSTALL    ${TTcent}" | pv -qL 80
    msg -bar
    echo " "
    clear&&clear
    return
}

# ---------------- definiciones de msg y utilidades ----------------
COLOR_VIOLETA='\033[38;5;129m'
RESET='\033[0m'

msg() {
  local colors="/etc/new-adm-color"
  if [[ ! -e $colors ]]; then
    COLOR[0]='\033[1;37m'
    COLOR[1]='\e[31m'
    COLOR[2]='\e[32m'
    COLOR[3]='\e[33m'
    COLOR[4]='\e[34m'
    COLOR[5]='\e[35m'
    COLOR[6]='\033[1;97m'
    COLOR[7]='\033[1;49;95m'
    COLOR[8]='\033[1;49;96m'
    COLOR[9]='\033[38;5;129m'
  else
    local COL=0
    for number in $(cat $colors); do
      case $number in
        1)COLOR[$COL]='\033[1;37m';;
        2)COLOR[$COL]='\e[31m';;
        3)COLOR[$COL]='\e[32m';;
        4)COLOR[$COL]='\e[33m';;
        5)COLOR[$COL]='\e[34m';;
        6)COLOR[$COL]='\e[35m';;
        7)COLOR[$COL]='\033[1;36m';;
        8)COLOR[$COL]='\033[1;49;95m';;
        9)COLOR[$COL]='\033[1;49;96m';;
      esac
      let COL++
    done
  fi

  NEGRITO='\e[1m'
  SEMCOR='\e[0m'

  case $1 in
    -ne) cor="${COLOR[1]}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}" ;;
    -ama) cor="${COLOR[3]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -verm) cor="${COLOR[3]}${NEGRITO}[!] ${COLOR[1]}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -verm2) cor="${COLOR[1]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -aqua) cor="${COLOR[8]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -azu) cor="${COLOR[6]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -verd) cor="${COLOR[2]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -bra) cor="${COLOR[0]}${SEMCOR}" && echo -e "${cor}${2}${SEMCOR}" ;;
    -bar)
      WIDTH=50
      echo -e "${COLOR_VIOLETA}$(printf '%.0s━' $(seq 1 $WIDTH))${RESET}"
    ;;
    -bar1)
      WIDTH=50
      echo -e "${COLOR_VIOLETA}$(printf '%.0s━' $(seq 1 $WIDTH))${RESET}"
    ;;
    -bar2)
      echo -e "${COLOR[4]}=====================================================${SEMCOR}"
    ;;
    -bar3)
      echo -e "${COLOR_VIOLETA}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    ;;
    -bar4)
      echo -e "${COLOR[5]}•••••••••••••••••••••••••••••••••••••••••••••••••${SEMCOR}"
    ;;
    -bar5)
      WIDTH=50
      echo -e "${COLOR_VIOLETA}$(printf '%.0s━' $(seq 1 $WIDTH))${RESET}"
    ;;
  esac
}

cor[0]="\033[0m"
cor[1]="\033[1;34m"
cor[2]="\033[1;32m"
cor[3]="\033[1;37m"
cor[4]="\033[1;36m"
cor[5]="\033[1;33m"
cor[6]="\033[1;35m"
export -f msg

# ============================================================
# EJECUCION PRINCIPAL
# ============================================================
clear&&clear
TIME_START="$(date +%s)"
msg -bar
update_pak
clear&&clear
funkey
clear&&clear
msg -bar
echo -e " Duracion $((($(date +%s)-$TIME_START)/60)) min."
echo ""
if [[ -e "$(which menu 2>/dev/null)" ]]; then
    $(which menu)
else
    echo -e " INSTALACION NO COMPLETADA CON EXITO !"
fi
echo " INSTALACION FINALIZADA "